import type { AppState } from "./types";

export const CATEGORIES = [
  "Handloom & Textiles",
  "Pottery & Terracotta",
  "Bags & Accessories",
  "Bamboo & Cane",
  "Jewellery",
  "Food & Spices",
  "Wood Craft",
  "Other",
];

export const demoState: AppState = {
  onboarded: false,
  business: {
    name: "Mitti & Dhaga Crafts",
    owner: "Sunita Devi",
    type: "Artisan",
    category: "Handloom & Textiles",
    village: "Bhilwara Khurd",
    block: "Kotri",
    district: "Bhilwara",
    state: "Rajasthan",
    pin: "311001",
    about:
      "A family of weavers and potters making handwoven cotton shawls, terracotta pottery and embroidered bags using techniques passed down four generations.",
    goals: ["Sell online", "Get better pricing", "Promote my business"],
    verified: true,
    language: "en",
  },
  products: [
    {
      id: "p1",
      name: "Handwoven Cotton Shawl",
      nameLocal: "हाथ से बुना सूती शॉल",
      category: "Handloom & Textiles",
      price: 1249,
      cost: 780,
      stock: 24,
      reorderLevel: 8,
      sold: 46,
      image: "shawl",
      status: "active",
      material: "Handspun cotton, natural indigo dye",
      bestSeller: true,
      description:
        "Softly woven on a pit loom, dyed with natural indigo. Light enough for summer evenings, warm enough for winter mornings.",
    },
    {
      id: "p2",
      name: "Terracotta Vase",
      nameLocal: "मिट्टी का फूलदान",
      category: "Pottery & Terracotta",
      price: 640,
      cost: 310,
      stock: 18,
      reorderLevel: 6,
      sold: 31,
      image: "vase",
      status: "active",
      material: "River clay, natural glaze",
      description: "Wheel-thrown river clay vase, sun-dried and kiln-fired in the village kiln.",
    },
    {
      id: "p3",
      name: "Embroidered Bag",
      nameLocal: "कढ़ाई वाला थैला",
      category: "Bags & Accessories",
      price: 389,
      cost: 210,
      stock: 4,
      reorderLevel: 10,
      sold: 58,
      image: "bag",
      status: "active",
      material: "Cotton canvas, silk thread",
      description: "Hand-embroidered cotton tote with mirror work along the rim.",
    },
    {
      id: "p4",
      name: "Handmade Cane Basket",
      nameLocal: "बेंत की टोकरी",
      category: "Bamboo & Cane",
      price: 480,
      cost: 240,
      stock: 12,
      reorderLevel: 6,
      sold: 22,
      image: "basket",
      status: "active",
      material: "Cane and bamboo",
      description: "Tightly woven cane basket for storage or fruit, finished with a natural wax.",
    },
    {
      id: "p5",
      name: "Traditional Dupatta",
      nameLocal: "पारंपरिक दुपट्टा",
      category: "Handloom & Textiles",
      price: 899,
      cost: 520,
      stock: 0,
      reorderLevel: 5,
      sold: 37,
      image: "dupatta",
      status: "active",
      material: "Cotton silk blend",
      description: "Block-printed dupatta with a hand-knotted tassel finish.",
    },
  ],
  orders: [
    {
      id: "ORD-2418",
      customer: "Priya Sharma",
      phone: "+91 98290 44120",
      items: [{ productId: "p1", name: "Handwoven Cotton Shawl", qty: 1, price: 1249 }],
      amount: 1249,
      address: "12 Nehru Marg, Jaipur, Rajasthan 302001",
      payment: "Paid online",
      status: "new",
      date: "Today, 9:12 AM",
    },
    {
      id: "ORD-2417",
      customer: "Ravi Kumar",
      phone: "+91 97840 11205",
      items: [
        { productId: "p3", name: "Embroidered Bag", qty: 2, price: 389 },
        { productId: "p2", name: "Terracotta Vase", qty: 1, price: 640 },
      ],
      amount: 1418,
      address: "Shop 4, Station Road, Ajmer, Rajasthan 305001",
      payment: "Cash on delivery",
      status: "processing",
      date: "Today, 8:04 AM",
    },
    {
      id: "ORD-2415",
      customer: "Meena Traders",
      phone: "+91 99280 76510",
      items: [{ productId: "p4", name: "Handmade Cane Basket", qty: 10, price: 460 }],
      amount: 4600,
      address: "Warehouse 7, MI Road, Jaipur, Rajasthan 302001",
      payment: "Paid online",
      status: "shipped",
      date: "Yesterday",
    },
    {
      id: "ORD-2410",
      customer: "Anjali Rao",
      phone: "+91 90045 22178",
      items: [{ productId: "p5", name: "Traditional Dupatta", qty: 1, price: 899 }],
      amount: 899,
      address: "44 Green Park, Udaipur, Rajasthan 313001",
      payment: "Paid online",
      status: "delivered",
      date: "3 days ago",
    },
    {
      id: "ORD-2402",
      customer: "Karan Mehta",
      phone: "+91 98111 09876",
      items: [{ productId: "p2", name: "Terracotta Vase", qty: 1, price: 640 }],
      amount: 640,
      address: "9 Civil Lines, Kota, Rajasthan 324001",
      payment: "Cash on delivery",
      status: "cancelled",
      date: "5 days ago",
    },
  ],
  customers: [
    { id: "c1", name: "Priya Sharma", phone: "+91 98290 44120", place: "Jaipur", orders: 6, spent: 7420, lastPurchase: "Today", tag: "Regular" },
    { id: "c2", name: "Meena Traders", phone: "+91 99280 76510", place: "Jaipur", orders: 4, spent: 18600, lastPurchase: "Yesterday", tag: "Bulk buyer" },
    { id: "c3", name: "Ravi Kumar", phone: "+91 97840 11205", place: "Ajmer", orders: 2, spent: 2058, lastPurchase: "Today", tag: "New" },
    { id: "c4", name: "Anjali Rao", phone: "+91 90045 22178", place: "Udaipur", orders: 3, spent: 3140, lastPurchase: "3 days ago", tag: "Regular" },
    { id: "c5", name: "Karan Mehta", phone: "+91 98111 09876", place: "Kota", orders: 1, spent: 640, lastPurchase: "4 months ago", tag: "Inactive" },
  ],
  expenses: [
    { id: "e1", label: "Cotton yarn purchase", amount: 8400, category: "Raw material", date: "This month" },
    { id: "e2", label: "Weaver wages", amount: 12000, category: "Labour", date: "This month" },
    { id: "e3", label: "Packaging boxes", amount: 1800, category: "Packaging", date: "This month" },
    { id: "e4", label: "Courier charges", amount: 2400, category: "Transport", date: "This month" },
    { id: "e5", label: "Loom shed rent", amount: 3000, category: "Rent", date: "This month" },
    { id: "e6", label: "Phone & internet", amount: 700, category: "Utilities", date: "This month" },
  ],
  store: {
    published: false,
    slug: "mitti-dhaga",
    theme: "artisan",
    tagline: "Handwoven in Bhilwara, made to last generations",
    whatsapp: "+91 98290 11223",
    featured: ["p1", "p2", "p3"],
  },
  promotions: [
    { id: "pr1", title: "Indigo shawl weaving reel", kind: "Reel", status: "Published" },
    { id: "pr2", title: "Diwali terracotta offer", kind: "Festival offer", status: "Approved" },
    { id: "pr3", title: "Embroidered bag close-up", kind: "Product", status: "Pending" },
  ],
  lessons: { l1: true, l2: true, l3: true, l4: true },
  notificationsRead: false,
  largeText: false,
  highContrast: false,
};

export const MONTHLY_SALES = [
  { month: "Apr", revenue: 32000, expenses: 21000 },
  { month: "May", revenue: 38500, expenses: 23400 },
  { month: "Jun", revenue: 30200, expenses: 22100 },
  { month: "Jul", revenue: 41800, expenses: 25600 },
  { month: "Aug", revenue: 47300, expenses: 26800 },
  { month: "Sep", revenue: 52900, expenses: 28300 },
];

export const DEMAND_FORECAST = [
  { month: "Jul", actual: 38, predicted: null as number | null },
  { month: "Aug", actual: 44, predicted: null as number | null },
  { month: "Sep", actual: 51, predicted: 51 },
  { month: "Oct", actual: null as number | null, predicted: 67 },
  { month: "Nov", actual: null as number | null, predicted: 82 },
  { month: "Dec", actual: null as number | null, predicted: 74 },
];

export const COMPETITORS = [
  { name: "Kotri Handloom Co-op", category: "Handloom", distance: "1.8 km", price: "₹1,100 – ₹1,600", rating: 4.2, type: "Direct", x: 30, y: 34 },
  { name: "Bhilwara Clay Works", category: "Pottery", distance: "3.2 km", price: "₹450 – ₹900", rating: 3.9, type: "Direct", x: 62, y: 25 },
  { name: "Shanti Textile Store", category: "Retail textiles", distance: "4.5 km", price: "₹600 – ₹1,200", rating: 4.4, type: "Indirect", x: 48, y: 62 },
  { name: "Rangoli Craft Emporium", category: "Mixed handicraft", distance: "6.1 km", price: "₹800 – ₹2,400", rating: 4.6, type: "Direct", x: 75, y: 70 },
  { name: "Village Weekly Haat", category: "Open market", distance: "2.4 km", price: "₹200 – ₹900", rating: 4.0, type: "Indirect", x: 20, y: 72 },
];

export const LOGISTICS_PARTNERS = [
  { name: "Bhilwara Local Courier", area: "Within 25 km", eta: "Same day", cost: "₹35 / parcel", status: "Available" },
  { name: "Rajasthan Speed Cargo", area: "State-wide", eta: "2–3 days", cost: "₹68 / parcel", status: "Available" },
  { name: "India Post Parcel", area: "All India", eta: "4–7 days", cost: "₹45 / parcel", status: "Available" },
  { name: "Kotri Tempo Service", area: "Bulk, within 60 km", eta: "Next day", cost: "₹900 / trip", status: "Available" },
];

export const LESSONS = [
  { id: "l1", title: "Start selling online", mins: 5, level: "Beginner", cat: "E-commerce" },
  { id: "l2", title: "Take good product photos with a phone", mins: 8, level: "Beginner", cat: "Photography" },
  { id: "l3", title: "How to price your craft fairly", mins: 6, level: "Beginner", cat: "Pricing" },
  { id: "l4", title: "Keeping simple stock records", mins: 5, level: "Beginner", cat: "Inventory" },
  { id: "l5", title: "Understanding profit and loss", mins: 10, level: "Intermediate", cat: "Finance" },
  { id: "l6", title: "WhatsApp marketing that works", mins: 7, level: "Beginner", cat: "Marketing" },
  { id: "l7", title: "Packing and shipping orders", mins: 6, level: "Beginner", cat: "Logistics" },
  { id: "l8", title: "Selling to bulk B2B buyers", mins: 12, level: "Intermediate", cat: "B2B" },
  { id: "l9", title: "Making reels of your craft", mins: 9, level: "Beginner", cat: "Social media" },
  { id: "l10", title: "Using AI tools in your business", mins: 8, level: "Beginner", cat: "AI tools" },
];
