import type { LangCode } from "./types";

/**
 * Phrase dictionary keyed by the exact English string used in the UI.
 * English always stays the main line; the local language is shown as a
 * smaller second line under it (see <Bi /> in components/ui-kit.tsx).
 */
type Phrases = Record<string, string>;

const hi: Phrases = {
  // navigation & shell
  Home: "होम",
  Products: "प्रोडक्ट",
  "AI Studio": "एआई स्टूडियो",
  Orders: "ऑर्डर",
  More: "और",
  Dashboard: "डैशबोर्ड",
  "My Business": "मेरा व्यापार",
  Inventory: "स्टॉक",
  Marketing: "प्रचार",
  Finance: "पैसा",
  "Business Advisor": "व्यापार सलाहकार",
  "My Store": "मेरी दुकान",
  Customers: "ग्राहक",
  Logistics: "डिलीवरी",
  "B2B Marketplace": "बड़े बाज़ार",
  Learning: "सीखें",
  Analytics: "रिपोर्ट",
  Notifications: "सूचनाएं",
  Profile: "प्रोफ़ाइल",
  Settings: "सेटिंग",
  Help: "मदद",
  "Online Presence": "ऑनलाइन पहचान",
  Close: "बंद करें",
  Save: "सेव करें",
  Cancel: "रद्द करें",
  Back: "वापस",
  Next: "आगे",
  Continue: "आगे बढ़ें",
  Done: "हो गया",
  Share: "साझा करें",
  Edit: "बदलें",
  Delete: "हटाएं",
  Speak: "बोलिए",
  // common screens
  "Add Product": "प्रोडक्ट जोड़ें",
  "Create Advertisement": "विज्ञापन बनाएं",
  "Check Price": "कीमत देखें",
  "Record Sale": "बिक्री दर्ज करें",
  "Check Finance": "हिसाब देखें",
  "Generate Content": "कंटेंट बनाएं",
  "Business Health": "व्यापार की सेहत",
  "View Business Health": "पूरी रिपोर्ट देखें",
  "Quick actions": "तुरंत काम",
  "Today's snapshot": "आज का हाल",
  "Your catalogue": "आपके प्रोडक्ट",
  "Ask AI": "एआई से पूछें",
  Sales: "बिक्री",
  Profit: "मुनाफ़ा",
  Expenses: "खर्च",
  Stock: "स्टॉक",
  Price: "कीमत",
  Cost: "लागत",
  Category: "श्रेणी",
  "Product name": "प्रोडक्ट का नाम",
  "Low stock": "स्टॉक कम",
  "Out of stock": "स्टॉक खत्म",
  "Pending payments": "बाकी पैसा",
  "Coming soon": "जल्द आ रहा है",
  "Fair Price Assistant": "सही कीमत सहायक",
  "AI Product Studio": "एआई फोटो स्टूडियो",
  "Voice Cataloguing": "आवाज़ से सूची",
  "Content Transformer": "कंटेंट बनाने वाला",
  "Advertisement Generator": "विज्ञापन बनाने वाला",
  "Reel Generator": "रील बनाने वाला",
  "Profit & Loss": "लाभ-हानि",
  "Scheme Calculator": "योजना कैलकुलेटर",
  "EMI Calculator": "किस्त कैलकुलेटर",
  "Local Market Research": "स्थानीय बाज़ार जानकारी",
  "Competitor Mapping": "प्रतियोगी नक्शा",
  "Build My Online Store": "मेरी ऑनलाइन दुकान बनाएं",
  "Publish Store": "दुकान प्रकाशित करें",
  "Store Preview": "दुकान देखें",
  Language: "भाषा",
  "Choose your language": "अपनी भाषा चुनिए",
};

const pa: Phrases = {
  Home: "ਘਰ",
  Products: "ਉਤਪਾਦ",
  "AI Studio": "ਏਆਈ ਸਟੂਡੀਓ",
  Orders: "ਆਰਡਰ",
  More: "ਹੋਰ",
  "My Business": "ਮੇਰਾ ਕਾਰੋਬਾਰ",
  Inventory: "ਸਟਾਕ",
  Marketing: "ਪ੍ਰਚਾਰ",
  Finance: "ਹਿਸਾਬ",
  "My Store": "ਮੇਰੀ ਦੁਕਾਨ",
  Customers: "ਗਾਹਕ",
  Logistics: "ਡਿਲੀਵਰੀ",
  Learning: "ਸਿੱਖੋ",
  Analytics: "ਰਿਪੋਰਟ",
  Settings: "ਸੈਟਿੰਗ",
  Help: "ਮਦਦ",
  Close: "ਬੰਦ ਕਰੋ",
  Save: "ਸੰਭਾਲੋ",
  Continue: "ਅੱਗੇ ਵਧੋ",
  Speak: "ਬੋਲੋ",
  "Add Product": "ਉਤਪਾਦ ਜੋੜੋ",
  "Create Advertisement": "ਇਸ਼ਤਿਹਾਰ ਬਣਾਓ",
  "Check Price": "ਕੀਮਤ ਵੇਖੋ",
  "Record Sale": "ਵਿਕਰੀ ਦਰਜ ਕਰੋ",
  "Business Health": "ਕਾਰੋਬਾਰ ਦੀ ਸਿਹਤ",
  Sales: "ਵਿਕਰੀ",
  Profit: "ਮੁਨਾਫ਼ਾ",
  Price: "ਕੀਮਤ",
  Stock: "ਸਟਾਕ",
  Language: "ਭਾਸ਼ਾ",
  "Choose your language": "ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ",
};

const mr: Phrases = {
  Home: "मुख्यपृष्ठ",
  Products: "उत्पादने",
  "AI Studio": "एआय स्टुडिओ",
  Orders: "ऑर्डर",
  More: "अधिक",
  "My Business": "माझा व्यवसाय",
  Inventory: "साठा",
  Marketing: "प्रचार",
  Finance: "हिशेब",
  "My Store": "माझे दुकान",
  Customers: "ग्राहक",
  Logistics: "पोहोच",
  Learning: "शिका",
  Analytics: "अहवाल",
  Settings: "सेटिंग",
  Help: "मदत",
  Close: "बंद करा",
  Save: "जतन करा",
  Continue: "पुढे चला",
  Speak: "बोला",
  "Add Product": "उत्पादन जोडा",
  "Create Advertisement": "जाहिरात तयार करा",
  "Check Price": "किंमत पहा",
  "Record Sale": "विक्री नोंदवा",
  "Business Health": "व्यवसायाचे आरोग्य",
  Sales: "विक्री",
  Profit: "नफा",
  Price: "किंमत",
  Stock: "साठा",
  Language: "भाषा",
  "Choose your language": "तुमची भाषा निवडा",
};

const gu: Phrases = {
  Home: "ઘર",
  Products: "ઉત્પાદનો",
  "AI Studio": "એઆઈ સ્ટુડિયો",
  Orders: "ઓર્ડર",
  More: "વધુ",
  "My Business": "મારો ધંધો",
  Inventory: "સ્ટોક",
  Marketing: "પ્રચાર",
  Finance: "હિસાબ",
  "My Store": "મારી દુકાન",
  Customers: "ગ્રાહકો",
  Logistics: "ડિલિવરી",
  Learning: "શીખો",
  Analytics: "અહેવાલ",
  Settings: "સેટિંગ",
  Help: "મદદ",
  Close: "બંધ કરો",
  Save: "સાચવો",
  Continue: "આગળ વધો",
  Speak: "બોલો",
  "Add Product": "ઉત્પાદન ઉમેરો",
  "Create Advertisement": "જાહેરાત બનાવો",
  "Check Price": "કિંમત જુઓ",
  "Record Sale": "વેચાણ નોંધો",
  "Business Health": "ધંધાની તંદુરસ્તી",
  Sales: "વેચાણ",
  Profit: "નફો",
  Price: "કિંમત",
  Stock: "સ્ટોક",
  Language: "ભાષા",
  "Choose your language": "તમારી ભાષા પસંદ કરો",
};

const bn: Phrases = {
  Home: "হোম",
  Products: "পণ্য",
  "AI Studio": "এআই স্টুডিও",
  Orders: "অর্ডার",
  More: "আরও",
  "My Business": "আমার ব্যবসা",
  Inventory: "মজুত",
  Marketing: "প্রচার",
  Finance: "হিসাব",
  "My Store": "আমার দোকান",
  Customers: "ক্রেতা",
  Logistics: "ডেলিভারি",
  Learning: "শিখুন",
  Analytics: "রিপোর্ট",
  Settings: "সেটিংস",
  Help: "সাহায্য",
  Close: "বন্ধ করুন",
  Save: "সংরক্ষণ",
  Continue: "এগিয়ে যান",
  Speak: "বলুন",
  "Add Product": "পণ্য যোগ করুন",
  "Create Advertisement": "বিজ্ঞাপন বানান",
  "Check Price": "দাম দেখুন",
  "Record Sale": "বিক্রি লিখুন",
  "Business Health": "ব্যবসার স্বাস্থ্য",
  Sales: "বিক্রি",
  Profit: "লাভ",
  Price: "দাম",
  Stock: "মজুত",
  Language: "ভাষা",
  "Choose your language": "আপনার ভাষা বাছুন",
};

const ta: Phrases = {
  Home: "முகப்பு",
  Products: "பொருட்கள்",
  "AI Studio": "ஏஐ ஸ்டுடியோ",
  Orders: "ஆர்டர்",
  More: "மேலும்",
  "My Business": "என் வணிகம்",
  Inventory: "கையிருப்பு",
  Marketing: "விளம்பரம்",
  Finance: "கணக்கு",
  "My Store": "என் கடை",
  Customers: "வாடிக்கையாளர்",
  Logistics: "விநியோகம்",
  Learning: "கற்க",
  Analytics: "அறிக்கை",
  Settings: "அமைப்புகள்",
  Help: "உதவி",
  Close: "மூடு",
  Save: "சேமி",
  Continue: "தொடரவும்",
  Speak: "பேசுங்கள்",
  "Add Product": "பொருள் சேர்",
  "Create Advertisement": "விளம்பரம் உருவாக்கு",
  "Check Price": "விலை பார்",
  "Record Sale": "விற்பனை பதிவு",
  "Business Health": "வணிக ஆரோக்கியம்",
  Sales: "விற்பனை",
  Profit: "லாபம்",
  Price: "விலை",
  Stock: "கையிருப்பு",
  Language: "மொழி",
  "Choose your language": "உங்கள் மொழியைத் தேர்வுசெய்க",
};

const te: Phrases = {
  Home: "హోమ్",
  Products: "ఉత్పత్తులు",
  "AI Studio": "ఏఐ స్టూడియో",
  Orders: "ఆర్డర్లు",
  More: "మరిన్ని",
  "My Business": "నా వ్యాపారం",
  Inventory: "సరుకు",
  Marketing: "ప్రచారం",
  Finance: "లెక్కలు",
  "My Store": "నా దుకాణం",
  Customers: "కస్టమర్లు",
  Logistics: "డెలివరీ",
  Learning: "నేర్చుకోండి",
  Analytics: "నివేదిక",
  Settings: "సెట్టింగ్‌లు",
  Help: "సహాయం",
  Close: "మూసివేయి",
  Save: "భద్రపరచు",
  Continue: "ముందుకు",
  Speak: "మాట్లాడండి",
  "Add Product": "ఉత్పత్తిని జోడించు",
  "Create Advertisement": "ప్రకటన తయారు చేయి",
  "Check Price": "ధర చూడండి",
  "Record Sale": "అమ్మకం నమోదు",
  "Business Health": "వ్యాపార ఆరోగ్యం",
  Sales: "అమ్మకాలు",
  Profit: "లాభం",
  Price: "ధర",
  Stock: "సరుకు",
  Language: "భాష",
  "Choose your language": "మీ భాషను ఎంచుకోండి",
};

const kn: Phrases = {
  Home: "ಮುಖಪುಟ",
  Products: "ಉತ್ಪನ್ನಗಳು",
  "AI Studio": "ಎಐ ಸ್ಟುಡಿಯೋ",
  Orders: "ಆರ್ಡರ್",
  More: "ಇನ್ನಷ್ಟು",
  "My Business": "ನನ್ನ ವ್ಯಾಪಾರ",
  Inventory: "ದಾಸ್ತಾನು",
  Marketing: "ಪ್ರಚಾರ",
  Finance: "ಲೆಕ್ಕ",
  "My Store": "ನನ್ನ ಅಂಗಡಿ",
  Customers: "ಗ್ರಾಹಕರು",
  Logistics: "ವಿತರಣೆ",
  Learning: "ಕಲಿಯಿರಿ",
  Analytics: "ವರದಿ",
  Settings: "ಸೆಟ್ಟಿಂಗ್ಸ್",
  Help: "ಸಹಾಯ",
  Close: "ಮುಚ್ಚಿ",
  Save: "ಉಳಿಸಿ",
  Continue: "ಮುಂದುವರಿಸಿ",
  Speak: "ಮಾತನಾಡಿ",
  "Add Product": "ಉತ್ಪನ್ನ ಸೇರಿಸಿ",
  "Create Advertisement": "ಜಾಹೀರಾತು ರಚಿಸಿ",
  "Check Price": "ಬೆಲೆ ನೋಡಿ",
  "Record Sale": "ಮಾರಾಟ ದಾಖಲಿಸಿ",
  "Business Health": "ವ್ಯಾಪಾರದ ಆರೋಗ್ಯ",
  Sales: "ಮಾರಾಟ",
  Profit: "ಲಾಭ",
  Price: "ಬೆಲೆ",
  Stock: "ದಾಸ್ತಾನು",
  Language: "ಭಾಷೆ",
  "Choose your language": "ನಿಮ್ಮ ಭಾಷೆ ಆರಿಸಿ",
};

const DICTS: Partial<Record<LangCode, Phrases>> = { hi, pa, mr, gu, bn, ta, te, kn };

const onboarding: Partial<Record<LangCode, Phrases>> = {
  hi: {
    "What kind of work do you do?": "आप किस तरह का काम करते हैं?", "Pick the closest one": "सबसे सही विकल्प चुनें",
    Artisan: "कारीगर", Farmer: "किसान", Manufacturer: "निर्माता", Retailer: "दुकानदार", "Service Provider": "सेवा प्रदाता", Other: "अन्य",
    "Your business details": "आपके व्यवसाय की जानकारी", "We use these to find local buyers and schemes for you": "इससे हम आपके लिए स्थानीय खरीदार और योजनाएं खोजते हैं",
    "Tell us about your business": "हमें अपने व्यवसाय के बारे में बताएं", "Business name": "व्यवसाय का नाम", "Owner name": "मालिक का नाम", Village: "गांव", Block: "ब्लॉक", District: "जिला", State: "राज्य", "PIN code": "पिन कोड",
    "Add your first product": "अपना पहला प्रोडक्ट जोड़ें", "A photo and a few words is enough — you can add more later": "एक फोटो और कुछ शब्द काफी हैं — बाद में और जोड़ सकते हैं", "Take Photo": "फोटो लें", "Upload Photo": "फोटो अपलोड करें", "Photo added — AI will clean it up for you later": "फोटो जुड़ गई — एआई इसे बाद में साफ करेगा", "Record voice description": "आवाज़ में विवरण रिकॉर्ड करें", "Skip for now": "अभी छोड़ें",
    "What do you want most?": "आप सबसे ज्यादा क्या चाहते हैं?", "Choose as many as you like": "जितने चाहें चुनें", "Sell locally": "स्थानीय रूप से बेचें", "Sell online": "ऑनलाइन बेचें", "Find B2B buyers": "थोक खरीदार खोजें", "Get better pricing": "बेहतर कीमत पाएं", "Get financial support": "आर्थिक सहायता पाएं", "Promote my business": "मेरे व्यवसाय का प्रचार करें", "Learn digital business": "डिजिटल व्यवसाय सीखें", "Finish setup": "सेटअप पूरा करें",
    "Your Digital Business is Ready!": "आपका डिजिटल व्यवसाय तैयार है!", "Your business profile": "आपकी व्यवसाय प्रोफ़ाइल", "Open My Dashboard": "मेरा डैशबोर्ड खोलें", "You can change any of this later by voice": "आप बाद में इसे आवाज़ से बदल सकते हैं",
  },
  pa: {
    "What kind of work do you do?": "ਤੁਸੀਂ ਕਿਸ ਤਰ੍ਹਾਂ ਦਾ ਕੰਮ ਕਰਦੇ ਹੋ?", "Pick the closest one": "ਸਭ ਤੋਂ ਨੇੜਲਾ ਵਿਕਲਪ ਚੁਣੋ", Artisan: "ਕਾਰੀਗਰ", Farmer: "ਕਿਸਾਨ", Manufacturer: "ਨਿਰਮਾਤਾ", Retailer: "ਦੁਕਾਨਦਾਰ", "Service Provider": "ਸੇਵਾ ਪ੍ਰਦਾਤਾ", Other: "ਹੋਰ", "Your business details": "ਤੁਹਾਡੇ ਕਾਰੋਬਾਰ ਦੀ ਜਾਣਕਾਰੀ", "We use these to find local buyers and schemes for you": "ਇਸ ਨਾਲ ਅਸੀਂ ਤੁਹਾਡੇ ਲਈ ਸਥਾਨਕ ਖਰੀਦਦਾਰ ਅਤੇ ਯੋਜਨਾਵਾਂ ਲੱਭਦੇ ਹਾਂ", "Tell us about your business": "ਸਾਨੂੰ ਆਪਣੇ ਕਾਰੋਬਾਰ ਬਾਰੇ ਦੱਸੋ", "Business name": "ਕਾਰੋਬਾਰ ਦਾ ਨਾਮ", "Owner name": "ਮਾਲਕ ਦਾ ਨਾਮ", Village: "ਪਿੰਡ", Block: "ਬਲਾਕ", District: "ਜ਼ਿਲ੍ਹਾ", State: "ਰਾਜ", "PIN code": "ਪਿੰਨ ਕੋਡ", Category: "ਸ਼੍ਰੇਣੀ", "Add your first product": "ਆਪਣਾ ਪਹਿਲਾ ਉਤਪਾਦ ਜੋੜੋ", "A photo and a few words is enough — you can add more later": "ਇੱਕ ਫੋਟੋ ਅਤੇ ਕੁਝ ਸ਼ਬਦ ਕਾਫ਼ੀ ਹਨ — ਹੋਰ ਬਾਅਦ ਵਿੱਚ ਜੋੜ ਸਕਦੇ ਹੋ", "Take Photo": "ਫੋਟੋ ਖਿੱਚੋ", "Upload Photo": "ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ", "Photo added — AI will clean it up for you later": "ਫੋਟੋ ਜੁੜ ਗਈ — ਏਆਈ ਬਾਅਦ ਵਿੱਚ ਸਾਫ਼ ਕਰੇਗਾ", "Product name": "ਉਤਪਾਦ ਦਾ ਨਾਮ", "Record voice description": "ਆਵਾਜ਼ ਵਿੱਚ ਵੇਰਵਾ ਰਿਕਾਰਡ ਕਰੋ", "Skip for now": "ਹੁਣੇ ਛੱਡੋ", "What do you want most?": "ਤੁਸੀਂ ਸਭ ਤੋਂ ਵੱਧ ਕੀ ਚਾਹੁੰਦੇ ਹੋ?", "Choose as many as you like": "ਜਿੰਨੇ ਚਾਹੋ ਚੁਣੋ", "Sell locally": "ਸਥਾਨਕ ਤੌਰ ਤੇ ਵੇਚੋ", "Sell online": "ਆਨਲਾਈਨ ਵੇਚੋ", "Find B2B buyers": "ਥੋਕ ਖਰੀਦਦਾਰ ਲੱਭੋ", "Get better pricing": "ਵਧੀਆ ਕੀਮਤ ਲਵੋ", "Get financial support": "ਵਿੱਤੀ ਮਦਦ ਲਵੋ", "Promote my business": "ਮੇਰੇ ਕਾਰੋਬਾਰ ਦਾ ਪ੍ਰਚਾਰ ਕਰੋ", "Learn digital business": "ਡਿਜੀਟਲ ਕਾਰੋਬਾਰ ਸਿੱਖੋ", "Finish setup": "ਸੈੱਟਅੱਪ ਪੂਰਾ ਕਰੋ", "Your Digital Business is Ready!": "ਤੁਹਾਡਾ ਡਿਜੀਟਲ ਕਾਰੋਬਾਰ ਤਿਆਰ ਹੈ!", "Your business profile": "ਤੁਹਾਡੀ ਕਾਰੋਬਾਰੀ ਪ੍ਰੋਫਾਈਲ", "Open My Dashboard": "ਮੇਰਾ ਡੈਸ਼ਬੋਰਡ ਖੋਲ੍ਹੋ", "You can change any of this later by voice": "ਤੁਸੀਂ ਇਹ ਬਾਅਦ ਵਿੱਚ ਆਵਾਜ਼ ਨਾਲ ਬਦਲ ਸਕਦੇ ਹੋ",
  },
  mr: {
    "What kind of work do you do?": "तुम्ही कोणत्या प्रकारचे काम करता?", "Pick the closest one": "सर्वात जवळचा पर्याय निवडा", Artisan: "कारागीर", Farmer: "शेतकरी", Manufacturer: "उत्पादक", Retailer: "किरकोळ विक्रेता", "Service Provider": "सेवा पुरवठादार", Other: "इतर", "Your business details": "तुमच्या व्यवसायाची माहिती", "We use these to find local buyers and schemes for you": "यामुळे आम्ही तुमच्यासाठी स्थानिक खरेदीदार आणि योजना शोधतो", "Tell us about your business": "तुमच्या व्यवसायाबद्दल सांगा", "Business name": "व्यवसायाचे नाव", "Owner name": "मालकाचे नाव", Village: "गाव", Block: "तालुका", District: "जिल्हा", State: "राज्य", "PIN code": "पिन कोड", Category: "श्रेणी", "Add your first product": "तुमचे पहिले उत्पादन जोडा", "A photo and a few words is enough — you can add more later": "एक फोटो आणि काही शब्द पुरेसे आहेत — नंतर आणखी जोडू शकता", "Take Photo": "फोटो काढा", "Upload Photo": "फोटो अपलोड करा", "Photo added — AI will clean it up for you later": "फोटो जोडला — एआय नंतर तो स्वच्छ करेल", "Product name": "उत्पादनाचे नाव", "Record voice description": "आवाजात वर्णन रेकॉर्ड करा", "Skip for now": "आत्ता वगळा", "What do you want most?": "तुम्हाला सर्वात जास्त काय हवे आहे?", "Choose as many as you like": "हवे तितके निवडा", "Sell locally": "स्थानिक पातळीवर विका", "Sell online": "ऑनलाइन विका", "Find B2B buyers": "घाऊक खरेदीदार शोधा", "Get better pricing": "चांगली किंमत मिळवा", "Get financial support": "आर्थिक मदत मिळवा", "Promote my business": "माझ्या व्यवसायाचा प्रचार करा", "Learn digital business": "डिजिटल व्यवसाय शिका", "Finish setup": "सेटअप पूर्ण करा", "Your Digital Business is Ready!": "तुमचा डिजिटल व्यवसाय तयार आहे!", "Your business profile": "तुमची व्यवसाय प्रोफाइल", "Open My Dashboard": "माझा डॅशबोर्ड उघडा", "You can change any of this later by voice": "तुम्ही हे नंतर आवाजाने बदलू शकता",
  },
  gu: {
    "What kind of work do you do?": "તમે કયા પ્રકારનું કામ કરો છો?", "Pick the closest one": "સૌથી નજીકનો વિકલ્પ પસંદ કરો", Artisan: "કારીગર", Farmer: "ખેડૂત", Manufacturer: "ઉત્પાદક", Retailer: "છૂટક વેપારી", "Service Provider": "સેવા પ્રદાતા", Other: "અન્ય", "Your business details": "તમારા ધંધાની વિગતો", "We use these to find local buyers and schemes for you": "આનાથી અમે તમારા માટે સ્થાનિક ખરીદદારો અને યોજનાઓ શોધીએ છીએ", "Tell us about your business": "અમને તમારા ધંધા વિશે કહો", "Business name": "ધંધાનું નામ", "Owner name": "માલિકનું નામ", Village: "ગામ", Block: "તાલુકો", District: "જિલ્લો", State: "રાજ્ય", "PIN code": "પિન કોડ", Category: "શ્રેણી", "Add your first product": "તમારું પહેલું ઉત્પાદન ઉમેરો", "A photo and a few words is enough — you can add more later": "એક ફોટો અને થોડા શબ્દો પૂરતા છે — પછી વધુ ઉમેરી શકો છો", "Take Photo": "ફોટો લો", "Upload Photo": "ફોટો અપલોડ કરો", "Photo added — AI will clean it up for you later": "ફોટો ઉમેરાયો — એઆઈ પછી તેને સાફ કરશે", "Product name": "ઉત્પાદનનું નામ", "Record voice description": "અવાજમાં વર્ણન રેકોર્ડ કરો", "Skip for now": "હમણાં છોડો", "What do you want most?": "તમારે સૌથી વધુ શું જોઈએ છે?", "Choose as many as you like": "જેટલા ઇચ્છો તેટલા પસંદ કરો", "Sell locally": "સ્થાનિક રીતે વેચો", "Sell online": "ઓનલાઇન વેચો", "Find B2B buyers": "જથ્થાબંધ ખરીદદારો શોધો", "Get better pricing": "વધુ સારી કિંમત મેળવો", "Get financial support": "નાણાકીય સહાય મેળવો", "Promote my business": "મારા ધંધાનો પ્રચાર કરો", "Learn digital business": "ડિજિટલ ધંધો શીખો", "Finish setup": "સેટઅપ પૂર્ણ કરો", "Your Digital Business is Ready!": "તમારો ડિજિટલ ધંધો તૈયાર છે!", "Your business profile": "તમારી ધંધાકીય પ્રોફાઇલ", "Open My Dashboard": "મારું ડેશબોર્ડ ખોલો", "You can change any of this later by voice": "તમે આ પછીથી અવાજ દ્વારા બદલી શકો છો",
  },
  bn: {
    "What kind of work do you do?": "আপনি কী ধরনের কাজ করেন?", "Pick the closest one": "সবচেয়ে কাছের বিকল্পটি বাছুন", Artisan: "কারিগর", Farmer: "কৃষক", Manufacturer: "উৎপাদক", Retailer: "খুচরা বিক্রেতা", "Service Provider": "সেবা প্রদানকারী", Other: "অন্যান্য", "Your business details": "আপনার ব্যবসার বিবরণ", "We use these to find local buyers and schemes for you": "এটি দিয়ে আমরা আপনার জন্য স্থানীয় ক্রেতা ও প্রকল্প খুঁজি", "Tell us about your business": "আপনার ব্যবসা সম্পর্কে বলুন", "Business name": "ব্যবসার নাম", "Owner name": "মালিকের নাম", Village: "গ্রাম", Block: "ব্লক", District: "জেলা", State: "রাজ্য", "PIN code": "পিন কোড", Category: "বিভাগ", "Add your first product": "আপনার প্রথম পণ্য যোগ করুন", "A photo and a few words is enough — you can add more later": "একটি ছবি ও কয়েকটি শব্দই যথেষ্ট — পরে আরও যোগ করতে পারবেন", "Take Photo": "ছবি তুলুন", "Upload Photo": "ছবি আপলোড করুন", "Photo added — AI will clean it up for you later": "ছবি যোগ হয়েছে — এআই পরে পরিষ্কার করে দেবে", "Product name": "পণ্যের নাম", "Record voice description": "কণ্ঠে বিবরণ রেকর্ড করুন", "Skip for now": "এখন বাদ দিন", "What do you want most?": "আপনি সবচেয়ে বেশি কী চান?", "Choose as many as you like": "যতগুলি চান বাছুন", "Sell locally": "স্থানীয়ভাবে বিক্রি করুন", "Sell online": "অনলাইনে বিক্রি করুন", "Find B2B buyers": "পাইকারি ক্রেতা খুঁজুন", "Get better pricing": "ভালো দাম পান", "Get financial support": "আর্থিক সহায়তা পান", "Promote my business": "আমার ব্যবসার প্রচার করুন", "Learn digital business": "ডিজিটাল ব্যবসা শিখুন", "Finish setup": "সেটআপ শেষ করুন", "Your Digital Business is Ready!": "আপনার ডিজিটাল ব্যবসা প্রস্তুত!", "Your business profile": "আপনার ব্যবসার প্রোফাইল", "Open My Dashboard": "আমার ড্যাশবোর্ড খুলুন", "You can change any of this later by voice": "আপনি পরে কণ্ঠ দিয়ে এগুলি বদলাতে পারবেন",
  },
  ta: {
    "What kind of work do you do?": "நீங்கள் என்ன வகையான வேலை செய்கிறீர்கள்?", "Pick the closest one": "மிகப் பொருத்தமானதைத் தேர்ந்தெடுக்கவும்", Artisan: "கைவினைஞர்", Farmer: "விவசாயி", Manufacturer: "உற்பத்தியாளர்", Retailer: "சில்லறை விற்பனையாளர்", "Service Provider": "சேவை வழங்குநர்", Other: "மற்றவை", "Your business details": "உங்கள் வணிக விவரங்கள்", "We use these to find local buyers and schemes for you": "உள்ளூர் வாங்குபவர்களையும் திட்டங்களையும் கண்டறிய இதைப் பயன்படுத்துகிறோம்", "Tell us about your business": "உங்கள் வணிகத்தைப் பற்றிச் சொல்லுங்கள்", "Business name": "வணிகத்தின் பெயர்", "Owner name": "உரிமையாளரின் பெயர்", Village: "கிராமம்", Block: "வட்டாரம்", District: "மாவட்டம்", State: "மாநிலம்", "PIN code": "அஞ்சல் குறியீடு", Category: "வகை", "Add your first product": "உங்கள் முதல் பொருளைச் சேர்க்கவும்", "A photo and a few words is enough — you can add more later": "ஒரு படமும் சில சொற்களும் போதும் — பின்னர் மேலும் சேர்க்கலாம்", "Take Photo": "படம் எடுக்கவும்", "Upload Photo": "படத்தைப் பதிவேற்றவும்", "Photo added — AI will clean it up for you later": "படம் சேர்க்கப்பட்டது — ஏஐ பின்னர் செம்மைப்படுத்தும்", "Product name": "பொருளின் பெயர்", "Record voice description": "குரல் விளக்கத்தைப் பதிவு செய்யவும்", "Skip for now": "இப்போது தவிர்க்கவும்", "What do you want most?": "உங்களுக்கு மிகவும் வேண்டியது என்ன?", "Choose as many as you like": "விரும்பிய அனைத்தையும் தேர்ந்தெடுக்கவும்", "Sell locally": "உள்ளூரில் விற்கவும்", "Sell online": "இணையத்தில் விற்கவும்", "Find B2B buyers": "மொத்த வாங்குபவர்களைக் கண்டறியவும்", "Get better pricing": "சிறந்த விலையைப் பெறவும்", "Get financial support": "நிதி உதவி பெறவும்", "Promote my business": "என் வணிகத்தை விளம்பரப்படுத்தவும்", "Learn digital business": "டிஜிட்டல் வணிகம் கற்கவும்", "Finish setup": "அமைப்பை முடிக்கவும்", "Your Digital Business is Ready!": "உங்கள் டிஜிட்டல் வணிகம் தயாராகிவிட்டது!", "Your business profile": "உங்கள் வணிகச் சுயவிவரம்", "Open My Dashboard": "என் டாஷ்போர்டைத் திறக்கவும்", "You can change any of this later by voice": "இவற்றை பின்னர் குரல் மூலம் மாற்றலாம்",
  },
  te: {
    "What kind of work do you do?": "మీరు ఎలాంటి పని చేస్తారు?", "Pick the closest one": "దగ్గరగా సరిపోయేదాన్ని ఎంచుకోండి", Artisan: "హస్తకళాకారుడు", Farmer: "రైతు", Manufacturer: "తయారీదారు", Retailer: "చిల్లర వ్యాపారి", "Service Provider": "సేవా ప్రదాత", Other: "ఇతర", "Your business details": "మీ వ్యాపార వివరాలు", "We use these to find local buyers and schemes for you": "స్థానిక కొనుగోలుదారులు, పథకాలను కనుగొనడానికి వీటిని ఉపయోగిస్తాము", "Tell us about your business": "మీ వ్యాపారం గురించి చెప్పండి", "Business name": "వ్యాపారం పేరు", "Owner name": "యజమాని పేరు", Village: "గ్రామం", Block: "మండలం", District: "జిల్లా", State: "రాష్ట్రం", "PIN code": "పిన్ కోడ్", Category: "వర్గం", "Add your first product": "మీ మొదటి ఉత్పత్తిని జోడించండి", "A photo and a few words is enough — you can add more later": "ఒక ఫోటో, కొన్ని మాటలు చాలు — తర్వాత మరిన్ని జోడించవచ్చు", "Take Photo": "ఫోటో తీయండి", "Upload Photo": "ఫోటో అప్‌లోడ్ చేయండి", "Photo added — AI will clean it up for you later": "ఫోటో జోడించబడింది — ఏఐ తర్వాత మెరుగుపరుస్తుంది", "Product name": "ఉత్పత్తి పేరు", "Record voice description": "వాయిస్ వివరణ రికార్డ్ చేయండి", "Skip for now": "ప్రస్తుతానికి దాటవేయండి", "What do you want most?": "మీకు అన్నింటికంటే ఎక్కువగా ఏం కావాలి?", "Choose as many as you like": "మీకు నచ్చినన్ని ఎంచుకోండి", "Sell locally": "స్థానికంగా అమ్మండి", "Sell online": "ఆన్‌లైన్‌లో అమ్మండి", "Find B2B buyers": "టోకు కొనుగోలుదారులను కనుగొనండి", "Get better pricing": "మంచి ధర పొందండి", "Get financial support": "ఆర్థిక సహాయం పొందండి", "Promote my business": "నా వ్యాపారాన్ని ప్రచారం చేయండి", "Learn digital business": "డిజిటల్ వ్యాపారం నేర్చుకోండి", "Finish setup": "సెటప్ పూర్తి చేయండి", "Your Digital Business is Ready!": "మీ డిజిటల్ వ్యాపారం సిద్ధంగా ఉంది!", "Your business profile": "మీ వ్యాపార ప్రొఫైల్", "Open My Dashboard": "నా డ్యాష్‌బోర్డ్ తెరవండి", "You can change any of this later by voice": "వీటిని తర్వాత వాయిస్‌తో మార్చవచ్చు",
  },
  kn: {
    "What kind of work do you do?": "ನೀವು ಯಾವ ರೀತಿಯ ಕೆಲಸ ಮಾಡುತ್ತೀರಿ?", "Pick the closest one": "ಹತ್ತಿರದ ಆಯ್ಕೆಯನ್ನು ಆರಿಸಿ", Artisan: "ಕುಶಲಕರ್ಮಿ", Farmer: "ರೈತ", Manufacturer: "ತಯಾರಕ", Retailer: "ಚಿಲ್ಲರೆ ವ್ಯಾಪಾರಿ", "Service Provider": "ಸೇವಾ ಪೂರೈಕೆದಾರ", Other: "ಇತರೆ", "Your business details": "ನಿಮ್ಮ ವ್ಯಾಪಾರದ ವಿವರಗಳು", "We use these to find local buyers and schemes for you": "ಸ್ಥಳೀಯ ಖರೀದಿದಾರರು ಮತ್ತು ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಲು ಇದನ್ನು ಬಳಸುತ್ತೇವೆ", "Tell us about your business": "ನಿಮ್ಮ ವ್ಯಾಪಾರದ ಬಗ್ಗೆ ತಿಳಿಸಿ", "Business name": "ವ್ಯಾಪಾರದ ಹೆಸರು", "Owner name": "ಮಾಲೀಕರ ಹೆಸರು", Village: "ಗ್ರಾಮ", Block: "ತಾಲೂಕು", District: "ಜಿಲ್ಲೆ", State: "ರಾಜ್ಯ", "PIN code": "ಪಿನ್ ಕೋಡ್", Category: "ವರ್ಗ", "Add your first product": "ನಿಮ್ಮ ಮೊದಲ ಉತ್ಪನ್ನವನ್ನು ಸೇರಿಸಿ", "A photo and a few words is enough — you can add more later": "ಒಂದು ಚಿತ್ರ ಮತ್ತು ಕೆಲವು ಪದಗಳು ಸಾಕು — ನಂತರ ಇನ್ನಷ್ಟು ಸೇರಿಸಬಹುದು", "Take Photo": "ಚಿತ್ರ ತೆಗೆಯಿರಿ", "Upload Photo": "ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ", "Photo added — AI will clean it up for you later": "ಚಿತ್ರ ಸೇರಿಸಲಾಗಿದೆ — ಎಐ ನಂತರ ಅದನ್ನು ಸುಧಾರಿಸುತ್ತದೆ", "Product name": "ಉತ್ಪನ್ನದ ಹೆಸರು", "Record voice description": "ಧ್ವನಿ ವಿವರಣೆ ದಾಖಲಿಸಿ", "Skip for now": "ಈಗ ಬಿಟ್ಟುಬಿಡಿ", "What do you want most?": "ನಿಮಗೆ ಹೆಚ್ಚು ಬೇಕಾಗಿರುವುದು ಏನು?", "Choose as many as you like": "ಇಷ್ಟವಾದಷ್ಟು ಆಯ್ಕೆ ಮಾಡಿ", "Sell locally": "ಸ್ಥಳೀಯವಾಗಿ ಮಾರಾಟ ಮಾಡಿ", "Sell online": "ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಮಾರಾಟ ಮಾಡಿ", "Find B2B buyers": "ಸಗಟು ಖರೀದಿದಾರರನ್ನು ಹುಡುಕಿ", "Get better pricing": "ಉತ್ತಮ ಬೆಲೆ ಪಡೆಯಿರಿ", "Get financial support": "ಹಣಕಾಸಿನ ನೆರವು ಪಡೆಯಿರಿ", "Promote my business": "ನನ್ನ ವ್ಯಾಪಾರವನ್ನು ಪ್ರಚಾರ ಮಾಡಿ", "Learn digital business": "ಡಿಜಿಟಲ್ ವ್ಯಾಪಾರ ಕಲಿಯಿರಿ", "Finish setup": "ಸೆಟಪ್ ಪೂರ್ಣಗೊಳಿಸಿ", "Your Digital Business is Ready!": "ನಿಮ್ಮ ಡಿಜಿಟಲ್ ವ್ಯಾಪಾರ ಸಿದ್ಧವಾಗಿದೆ!", "Your business profile": "ನಿಮ್ಮ ವ್ಯಾಪಾರದ ಪ್ರೊಫೈಲ್", "Open My Dashboard": "ನನ್ನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ತೆರೆಯಿರಿ", "You can change any of this later by voice": "ಇವುಗಳನ್ನು ನಂತರ ಧ್ವನಿಯ ಮೂಲಕ ಬದಲಾಯಿಸಬಹುದು",
  },
};

/** Returns the local-language line for an English UI string, or null. */
export function tr(lang: LangCode, english: string): string | null {
  if (lang === "en") return null;
  const dict = DICTS[lang];
  if (!dict) return null;
  const exact = dict[english] ?? onboarding[lang]?.[english];
  if (exact) return exact;
  const trimmed = english.trim();
  return dict[trimmed] ?? onboarding[lang]?.[trimmed] ?? null;
}
